name: Reusable Build

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    #   - uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building ${{ inputs.app-name }}"