name: Workflow, jobs, steps

on:
  workflow_dispatch:

jobs:
  first-pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: Say welcome
        run: echo "welcome github actions"
      - name: welcome
        needs: Say welcome
        run: echo "$date"
  
