name: Main Application Pipeline

on:
  push:
    branches:
      - master

jobs:
  # Call the reusable workflow for Staging
  call-stage-build:
    uses: ./.github/workflows/build.yml  # Path to local reusable file
    with:
      environment: STAGE
    secrets:
<<<<<<< HEAD
      ENV_VAR: ${{ secrets.ENV_VAR }}
=======
      API_TOKEN: ${{ secrets.ENV_SECRET }}
>>>>>>> parent of c6a72dd (UPDATING THE ISSUE)

  # Call the same reusable workflow for Production
  call-prod-build:
    needs: call-stage-build
    uses: ./.github/workflows/build.yml
    with:
      environment: PRODUCTION
    secrets:
<<<<<<< HEAD
      ENV_VAR: ${{ secrets.ENV_VAR_PROD }}
=======
      API_TOKEN: ${{ secrets.ENV_SECERET_PROD }}
>>>>>>> parent of c6a72dd (UPDATING THE ISSUE)
