name: Main Application Pipeline

on:
  push:
    branches:
      - master

jobs:
  # Call the reusable workflow for Staging
  call-stage-build:
    uses: ./.github/workflows/build.yml  # Path to local reusable file
    with:
      environment: STAGE
    secrets:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}

  # Call the same reusable workflow for Production
  call-prod-build:
    needs: call-stage-build
    uses: ./.github/workflows/build.yml
    with:
      environment: PRODUCTION
    secrets:
      ENV_SECRET: ${{ secrets.ENV_SECRET_PROD }}
